{{- if and .Values.gateway.enabled .Values.gateway.oidc.enabled (not .Values.gateway.oidc.existingSecret) .Values.gateway.oidc.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mailcatcher.fullname" . }}-oidc-client
  labels:
    {{- include "mailcatcher.labels" . | nindent 4 }}
type: Opaque
data:
  client-secret: {{ .Values.gateway.oidc.clientSecret | b64enc | quote }}
{{- end }}
