{{- $oidc := .Values.gateway.oidc }}
{{- if and .Values.gateway.enabled $oidc.enabled (not $oidc.existingSecret) $oidc.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mailcatcher.oidcSecretName" . }}
  labels:
    {{- include "mailcatcher.labels" . | nindent 4 }}
type: Opaque
data:
  client-secret: {{ $oidc.clientSecret | b64enc | quote }}
{{- end }}
